var c = document.getElementById('can');
var ctx = c.getContext('2d');
ctx.beginPath();
// ctx.moveTo(100,100);
// ctx.lineTo(0,0);
// ctx.arc(100,100,50,1.5*Math.PI,2*Math.PI,true);
// ctx.fillStyle = "red";
// ctx.fill();
// ctx.strokeStyle = "red";
ctx.font="50px Cursive";
ctx.fillText("sahil",100,100);
// ctx.lineWidth="10";
// ctx.lineCap="round";
// ctx.textAlign="center";
// ctx.rect(50,50,100,100);
// ctx.fillStyle="red";
// ctx.fill();
ctx.stroke();
ctx.closePath();
